name: Build and Deploy Resume

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Compile LaTeX
        uses: docker://blang/latex:ctanfull
        with:
          args: >
            sh -c "
            cd /github/workspace/CV
            pdflatex -interaction=nonstopmode CV.tex
            "

      - name: Prepare artifact
        run: |
          mkdir -p public
          cp CV.pdf public/CV.pdf

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: resume-pdf
          path: public

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: resume-pdf
          path: public

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4



