name: Build and Deploy Resume

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: docker://blang/latex:ctanfull
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Compile LaTeX
        run: |
          cd CV
          pdflatex -interaction=nonstopmode CV.tex
        
      - name: Move PDF to root
        run: mv CV/CV.pdf CV.pdf

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: resume-pdf
          
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: CD.pdf
          
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4



