name: Build and Deploy Resume

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Шаг выполняется НА ХОСТЕ (без контейнера)
      - name: Checkout code
        uses: actions/checkout@v4

      # Запуск компиляции в контейнере
      - name: Compile LaTeX
        uses: docker://blang/latex:ctanfull
        with:
          args: >
            sh -c "
            cd /github/workspace/CV
            pdflatex -interaction=nonstopmode CV.tex
            "

      # Переносим PDF и сохраняем артефакт
      - name: Prepare artifact
        run: |
          mv CV/CV.pdf CV.pdf
          echo "PDF generated at $(pwd)/CV.pdf"

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: resume-pdf
          path: CV.pdf

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: resume-pdf

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: CV.pdf  # Исправлено имя файла

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4



